#!/usr/bin/env bash

###############################################
#   USAGE                                     #
###############################################

usage() {
    echo "Usage: $(basename $0) YEAR DATE"
    echo
    echo "Fetch AoC custom input files from the AoC remote host."
    echo
    echo "ARGUMENTS"
    echo "    YEAR      The challenge year. Should be a year after 2015, but"
    echo "              is not currently sanitized."
    echo "    DATE      The challenge date. Should be a number 1-25, but is"
    echo "              not currently sanitized."
    echo
    echo "OPTIONS"
    echo "    -h        Display this help message."
    echo "    -v        Verbose program output."
    echo
    exit 0
}

###############################################
#   LOGGERS                                   #
###############################################

fatal() {
    echo -e "[\033[31m-\033[0m] $(basename ${BASH_SOURCE[0],,}): $1"
    exit 1
}

warning() {
    echo -e "[\033[33m*\033[0m] $(basename ${BASH_SOURCE[0],,}): $1"
}

debug() {
    (($DEBUG == 1)) || return 0
    echo -e "[\033[32m+\033[0m] $(basename ${BASH_SOURCE[0],,}): $1"
}

###############################################
#   DRIVERS                                   #
###############################################

fetch() {
    local year="$1"
    local date="$2"
    validate "$year" "$date"
    debug "Fetching: ${year@A} ${date@A}"

    # Get AOC_TOKEN from environment
    source utils/aoc-session || true
    [[ -n "$AOC_SESSION" ]] || fatal "missing AOC_SESSION env"

    # Output location
    local outfile=input/"$year"/day-"$(printf "%02d" "$date")".txt
    if [[ -f "$outfile" ]]; then
        warning "file exists: $outfile"
        return
    fi

    # cURL the contents
    tmpfile=$(mktemp)
    curl -sS --fail-with-body \
        -H "Cookie: session=$AOC_SESSION" \
        -H "User-Agent: heavycircle (+https://github.com/heavycircle)" \
        "https://adventofcode.com/$year/day/$date/input" -o "$tmpfile"

    # Copy on success
    if (($? == 0)); then
        mkdir -p "$(dirname "$outfile")"
        mv "$tmpfile" "$outfile"

        DEBUG=1 debug "file retrieved: $outfile"
    else
        warning "could not retrieve file"
    fi

}

fetch-all() {
    # Get current month
    read cur_year cur_month cur_day <<<"$(date '+%Y %-m %-d')"
    local last_day=25

    # Get ending values
    if ((cur_month == 12)); then
        last_day="$cur_day"
    else
        ((--cur_year))
    fi

    # Iterate
    for ((year = 2015; year <= cur_year; year++)); do
        for ((day = 1; day <= last_day; day++)); do
            fetch "$year" "$day"
        done
    done
}

main() {
    local -a positional
    declare -g DEBUG=0

    # Go to the root
    local root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    cd "$(dirname "$root")"

    # Drain flags
    while (($# > 0)); do
        case "$1" in
            -h | --help) usage ;;
            -v | --verbose) DEBUG=1 ;;
            -* | --*) fatal "unknown argument: $1" ;;
            *) positional+=("$1") ;;
        esac

        shift
    done

    # Positional arguments
    set -- "${positional[@]}"
    (($# < 3)) || fatal "incorrect argument count!"
    local year="$1"
    local date="$2"

    if [[ "$year" == "all" ]]; then
        # Fetch all
        fetch-all
    elif [[ -n "$date" ]]; then
        # Fetch the specific ref
        fetch "$year" "$date"
    else
        fatal "missing argument: date"
    fi

}

main "$@"
